-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from file:drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_powermap_assessment_history`;
DROP TABLE IF EXISTS `civicrm_powermap_access`;
DROP TABLE IF EXISTS `civicrm_powermap_stakeholder`;
DROP TABLE IF EXISTS `civicrm_powermap_config`;
DROP TABLE IF EXISTS `civicrm_powermap_audit_log`;

SET FOREIGN_KEY_CHECKS=1;

-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_powermap_audit_log
-- *
-- * Power Mapping Audit Log
-- *
-- *******************************************************/
CREATE TABLE `civicrm_powermap_audit_log` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Audit Log ID',
  `entity_table` varchar(64) NOT NULL COMMENT 'Table name of the entity',
  `entity_id` int unsigned NOT NULL COMMENT 'ID of the entity',
  `contact_id` int unsigned COMMENT 'FK to Contact ID who performed action',
  `action` varchar(32) NOT NULL COMMENT 'Action performed (create, update, delete, view)',
  `old_values` text COMMENT 'JSON encoded old values',
  `new_values` text COMMENT 'JSON encoded new values',
  `log_date` datetime NOT NULL COMMENT 'Date and time of action',
  `ip_address` varchar(45) COMMENT 'IP address of user',
  `user_agent` text COMMENT 'User agent string',
  PRIMARY KEY (`id`),
  INDEX `index_contact_id`(contact_id),
  INDEX `index_entity`(entity_table, entity_id),
  INDEX `index_log_date`(log_date),
  INDEX `index_action`(action),
  INDEX `index_entity_table`(entity_table),
  INDEX `index_entity_id`(entity_id),
  CONSTRAINT FK_civicrm_powermap_audit_log_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_powermap_config
-- *
-- * Power Map Configuration Table
-- *
-- *******************************************************/
CREATE TABLE `civicrm_powermap_config` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique PowerMap Config ID',
  `name` varchar(255) NOT NULL COMMENT 'Power Map Name',
  `description` text COMMENT 'Power Map Description',
  `campaign_id` int unsigned COMMENT 'Associated Campaign ID',
  `created_id` int unsigned COMMENT 'FK to Contact ID of creator',
  `created_date` datetime COMMENT 'Date and time power map was created',
  `modified_id` int unsigned COMMENT 'FK to Contact ID of last modifier',
  `modified_date` datetime COMMENT 'Date and time power map was last modified',
  `is_active` tinyint NOT NULL DEFAULT 1 COMMENT 'Is this power map active?',
  `is_reserved` tinyint NOT NULL DEFAULT 0 COMMENT 'Is this power map reserved?',
  `visibility` varchar(32) DEFAULT 'public' COMMENT 'Visibility setting (public, private, group)',
  `settings` text COMMENT 'JSON encoded settings for this power map',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_name`(name),
  INDEX `index_campaign_id`(campaign_id),
  INDEX `index_created_id`(created_id),
  INDEX `index_is_active`(is_active),
  INDEX `index_visibility`(visibility),
  INDEX `index_created_date`(created_date),
  CONSTRAINT FK_civicrm_powermap_config_campaign_id FOREIGN KEY (`campaign_id`) REFERENCES `civicrm_campaign`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_powermap_config_created_id FOREIGN KEY (`created_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_powermap_config_modified_id FOREIGN KEY (`modified_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_powermap_stakeholder
-- *
-- * Power Map Stakeholder Assignments
-- *
-- *******************************************************/
CREATE TABLE `civicrm_powermap_stakeholder` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique PowerMap Stakeholder ID',
  `powermap_id` int unsigned NOT NULL COMMENT 'FK to PowerMap Config',
  `contact_id` int unsigned NOT NULL COMMENT 'FK to Contact ID',
  `added_date` datetime COMMENT 'Date stakeholder was added to power map',
  `added_by` int unsigned COMMENT 'FK to Contact ID who added stakeholder',
  `is_active` tinyint NOT NULL DEFAULT 1 COMMENT 'Is this stakeholder assignment active?',
  `position_x` decimal(20,2) COMMENT 'X coordinate for manual positioning',
  `position_y` decimal(20,2) COMMENT 'Y coordinate for manual positioning',
  `notes` text COMMENT 'Additional notes about this stakeholder assignment',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UI_powermap_stakeholder`(powermap_id, contact_id),
  INDEX `index_powermap_id`(powermap_id),
  INDEX `index_contact_id`(contact_id),
  INDEX `index_added_by`(added_by),
  INDEX `index_is_active`(is_active),
  INDEX `index_added_date`(added_date),
  CONSTRAINT FK_civicrm_powermap_stakeholder_powermap_id FOREIGN KEY (`powermap_id`) REFERENCES `civicrm_powermap_config`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_powermap_stakeholder_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_powermap_stakeholder_added_by FOREIGN KEY (`added_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_powermap_access
-- *
-- * Power Map Access Control
-- *
-- *******************************************************/
CREATE TABLE `civicrm_powermap_access` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique PowerMap Access ID',
  `powermap_id` int unsigned NOT NULL COMMENT 'FK to PowerMap Config',
  `contact_id` int unsigned COMMENT 'FK to Contact ID for individual access',
  `group_id` int unsigned COMMENT 'FK to Group ID for group access',
  `permission_level` varchar(32) NOT NULL DEFAULT 'view' COMMENT 'Permission level (view, edit, admin)',
  `granted_date` datetime COMMENT 'Date access was granted',
  `granted_by` int unsigned COMMENT 'FK to Contact ID who granted access',
  `is_active` tinyint NOT NULL DEFAULT 1 COMMENT 'Is this access grant active?',
  PRIMARY KEY (`id`),
  INDEX `index_powermap_id`(powermap_id),
  INDEX `index_contact_id`(contact_id),
  INDEX `index_group_id`(group_id),
  INDEX `index_granted_by`(granted_by),
  INDEX `index_permission_level`(permission_level),
  INDEX `index_is_active`(is_active),
  INDEX `index_granted_date`(granted_date),
  CONSTRAINT FK_civicrm_powermap_access_powermap_id FOREIGN KEY (`powermap_id`) REFERENCES `civicrm_powermap_config`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_powermap_access_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_powermap_access_group_id FOREIGN KEY (`group_id`) REFERENCES `civicrm_group`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_powermap_access_granted_by FOREIGN KEY (`granted_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;

-- /*******************************************************
-- *
-- * civicrm_powermap_assessment_history
-- *
-- * Power Mapping Assessment History
-- *
-- *******************************************************/
CREATE TABLE `civicrm_powermap_assessment_history` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique Assessment History ID',
  `contact_id` int unsigned NOT NULL COMMENT 'FK to Contact ID',
  `powermap_id` int unsigned COMMENT 'FK to PowerMap Config (optional)',
  `influence_level` varchar(32) COMMENT 'Historical influence level',
  `support_level` varchar(32) COMMENT 'Historical support level',
  `engagement_priority` varchar(32) COMMENT 'Historical engagement priority',
  `stakeholder_type` text COMMENT 'Historical stakeholder types',
  `assessment_notes` text COMMENT 'Historical assessment notes',
  `assessed_date` datetime NOT NULL COMMENT 'Date of this assessment',
  `assessed_by` int unsigned COMMENT 'FK to Contact ID who made assessment',
  `change_reason` text COMMENT 'Reason for assessment change',
  PRIMARY KEY (`id`),
  INDEX `index_contact_id`(contact_id),
  INDEX `index_powermap_id`(powermap_id),
  INDEX `index_assessed_by`(assessed_by),
  INDEX `index_assessed_date`(assessed_date),
  INDEX `index_influence_level`(influence_level),
  INDEX `index_support_level`(support_level),
  INDEX `index_engagement_priority`(engagement_priority),
  CONSTRAINT FK_civicrm_powermap_assessment_history_contact_id FOREIGN KEY (`contact_id`) REFERENCES `civicrm_contact`(`id`) ON DELETE CASCADE,
  CONSTRAINT FK_civicrm_powermap_assessment_history_powermap_id FOREIGN KEY (`powermap_id`) REFERENCES `civicrm_powermap_config`(`id`) ON DELETE SET NULL,
  CONSTRAINT FK_civicrm_powermap_assessment_history_assessed_by FOREIGN KEY (`assessed_by`) REFERENCES `civicrm_contact`(`id`) ON DELETE SET NULL)
ENGINE=InnoDB;
