<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.powermap/xml/schema/CRM/Powermap/PowermapAuditLog.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:c46f3dadd7e65c746272d8049692086c)
 */
use CRM_Powermap_ExtensionUtil as E;

/**
 * Database access object for the PowermapAuditLog entity.
 */
class CRM_Powermap_DAO_PowermapAuditLog extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_powermap_audit_log';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique Audit Log ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Table name of the entity
   *
   * @var string
   *   (SQL type: varchar(64))
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_table;

  /**
   * ID of the entity
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $entity_id;

  /**
   * FK to Contact ID who performed action
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Action performed (create, update, delete, view)
   *
   * @var string
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $action;

  /**
   * JSON encoded old values
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $old_values;

  /**
   * JSON encoded new values
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $new_values;

  /**
   * Date and time of action
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $log_date;

  /**
   * IP address of user
   *
   * @var string|null
   *   (SQL type: varchar(45))
   *   Note that values will be retrieved from the database as a string.
   */
  public $ip_address;

  /**
   * User agent string
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $user_agent;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_powermap_audit_log';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Powermap Audit Logs') : E::ts('Powermap Audit Log');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Audit Log ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.id',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'entity_table' => [
          'name' => 'entity_table',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Entity Table'),
          'description' => E::ts('Table name of the entity'),
          'required' => TRUE,
          'maxlength' => 64,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.entity_table',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Entity Table"),
          ],
          'add' => NULL,
        ],
        'entity_id' => [
          'name' => 'entity_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Entity ID'),
          'description' => E::ts('ID of the entity'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.entity_id',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
            'label' => E::ts("Entity ID"),
          ],
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact ID who performed action'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.contact_id',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Contact"),
          ],
          'add' => NULL,
        ],
        'action' => [
          'name' => 'action',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Action'),
          'description' => E::ts('Action performed (create, update, delete, view)'),
          'required' => TRUE,
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.action',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Action"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Powermap_BAO_PowermapAuditLog::getActionOptions',
          ],
          'add' => NULL,
        ],
        'old_values' => [
          'name' => 'old_values',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Old Values'),
          'description' => E::ts('JSON encoded old values'),
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.old_values',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Old Values"),
          ],
          'add' => NULL,
        ],
        'new_values' => [
          'name' => 'new_values',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('New Values'),
          'description' => E::ts('JSON encoded new values'),
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.new_values',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("New Values"),
          ],
          'add' => NULL,
        ],
        'log_date' => [
          'name' => 'log_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Log Date'),
          'description' => E::ts('Date and time of action'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.log_date',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
            'label' => E::ts("Log Date"),
          ],
          'add' => NULL,
        ],
        'ip_address' => [
          'name' => 'ip_address',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Ip Address'),
          'description' => E::ts('IP address of user'),
          'maxlength' => 45,
          'size' => CRM_Utils_Type::BIG,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.ip_address',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("IP Address"),
          ],
          'add' => NULL,
        ],
        'user_agent' => [
          'name' => 'user_agent',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('User Agent'),
          'description' => E::ts('User agent string'),
          'rows' => 2,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_audit_log.user_agent',
          'table_name' => 'civicrm_powermap_audit_log',
          'entity' => 'PowermapAuditLog',
          'bao' => 'CRM_Powermap_DAO_PowermapAuditLog',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("User Agent"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'powermap_audit_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'powermap_audit_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_contact_id' => [
        'name' => 'index_contact_id',
        'field' => [
          0 => 'contact_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_audit_log::0::contact_id',
      ],
      'index_entity' => [
        'name' => 'index_entity',
        'field' => [
          0 => 'entity_table',
          1 => 'entity_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_audit_log::0::entity_table::entity_id',
      ],
      'index_log_date' => [
        'name' => 'index_log_date',
        'field' => [
          0 => 'log_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_audit_log::0::log_date',
      ],
      'index_action' => [
        'name' => 'index_action',
        'field' => [
          0 => 'action',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_audit_log::0::action',
      ],
      'index_entity_table' => [
        'name' => 'index_entity_table',
        'field' => [
          0 => 'entity_table',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_audit_log::0::entity_table',
      ],
      'index_entity_id' => [
        'name' => 'index_entity_id',
        'field' => [
          0 => 'entity_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_audit_log::0::entity_id',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
