<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.powermap/xml/schema/CRM/Powermap/PowermapAccess.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:1892006fe7b8f6a2c16bd0453f7abd73)
 */
use CRM_Powermap_ExtensionUtil as E;

/**
 * Database access object for the PowermapAccess entity.
 */
class CRM_Powermap_DAO_PowermapAccess extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_powermap_access';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique PowerMap Access ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to PowerMap Config
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $powermap_id;

  /**
   * FK to Contact ID for individual access
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * FK to Group ID for group access
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $group_id;

  /**
   * Permission level (view, edit, admin)
   *
   * @var string
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $permission_level;

  /**
   * Date access was granted
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $granted_date;

  /**
   * FK to Contact ID who granted access
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $granted_by;

  /**
   * Is this access grant active?
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_powermap_access';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Powermap Accesses') : E::ts('Powermap Access');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique PowerMap Access ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_access.id',
          'table_name' => 'civicrm_powermap_access',
          'entity' => 'PowermapAccess',
          'bao' => 'CRM_Powermap_DAO_PowermapAccess',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'powermap_id' => [
          'name' => 'powermap_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Powermap ID'),
          'description' => E::ts('FK to PowerMap Config'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_access.powermap_id',
          'table_name' => 'civicrm_powermap_access',
          'entity' => 'PowermapAccess',
          'bao' => 'CRM_Powermap_DAO_PowermapAccess',
          'localizable' => 0,
          'FKClassName' => 'CRM_Powermap_DAO_PowermapConfig',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Power Map"),
          ],
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact ID for individual access'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_access.contact_id',
          'table_name' => 'civicrm_powermap_access',
          'entity' => 'PowermapAccess',
          'bao' => 'CRM_Powermap_DAO_PowermapAccess',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Contact"),
          ],
          'add' => NULL,
        ],
        'group_id' => [
          'name' => 'group_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Group ID'),
          'description' => E::ts('FK to Group ID for group access'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_access.group_id',
          'table_name' => 'civicrm_powermap_access',
          'entity' => 'PowermapAccess',
          'bao' => 'CRM_Powermap_DAO_PowermapAccess',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Group',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Group"),
          ],
          'add' => NULL,
        ],
        'permission_level' => [
          'name' => 'permission_level',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Permission Level'),
          'description' => E::ts('Permission level (view, edit, admin)'),
          'required' => TRUE,
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_access.permission_level',
          'default' => 'view',
          'table_name' => 'civicrm_powermap_access',
          'entity' => 'PowermapAccess',
          'bao' => 'CRM_Powermap_DAO_PowermapAccess',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Permission Level"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Powermap_BAO_PowermapAccess::getPermissionLevelOptions',
          ],
          'add' => NULL,
        ],
        'granted_date' => [
          'name' => 'granted_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Granted Date'),
          'description' => E::ts('Date access was granted'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_access.granted_date',
          'table_name' => 'civicrm_powermap_access',
          'entity' => 'PowermapAccess',
          'bao' => 'CRM_Powermap_DAO_PowermapAccess',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
            'label' => E::ts("Granted Date"),
          ],
          'add' => NULL,
        ],
        'granted_by' => [
          'name' => 'granted_by',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Granted By'),
          'description' => E::ts('FK to Contact ID who granted access'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_access.granted_by',
          'table_name' => 'civicrm_powermap_access',
          'entity' => 'PowermapAccess',
          'bao' => 'CRM_Powermap_DAO_PowermapAccess',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Granted By"),
          ],
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Enabled'),
          'description' => E::ts('Is this access grant active?'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_access.is_active',
          'default' => '1',
          'table_name' => 'civicrm_powermap_access',
          'entity' => 'PowermapAccess',
          'bao' => 'CRM_Powermap_DAO_PowermapAccess',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
            'label' => E::ts("Active"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'powermap_access', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'powermap_access', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_powermap_id' => [
        'name' => 'index_powermap_id',
        'field' => [
          0 => 'powermap_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_access::0::powermap_id',
      ],
      'index_contact_id' => [
        'name' => 'index_contact_id',
        'field' => [
          0 => 'contact_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_access::0::contact_id',
      ],
      'index_group_id' => [
        'name' => 'index_group_id',
        'field' => [
          0 => 'group_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_access::0::group_id',
      ],
      'index_granted_by' => [
        'name' => 'index_granted_by',
        'field' => [
          0 => 'granted_by',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_access::0::granted_by',
      ],
      'index_permission_level' => [
        'name' => 'index_permission_level',
        'field' => [
          0 => 'permission_level',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_access::0::permission_level',
      ],
      'index_is_active' => [
        'name' => 'index_is_active',
        'field' => [
          0 => 'is_active',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_access::0::is_active',
      ],
      'index_granted_date' => [
        'name' => 'index_granted_date',
        'field' => [
          0 => 'granted_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_access::0::granted_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
