<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.powermap/xml/schema/CRM/Powermap/PowermapStakeholder.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:59b42c3a30d93ba2661d493a53543060)
 */
use CRM_Powermap_ExtensionUtil as E;

/**
 * Database access object for the PowermapStakeholder entity.
 */
class CRM_Powermap_DAO_PowermapStakeholder extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_powermap_stakeholder';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique PowerMap Stakeholder ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to PowerMap Config
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $powermap_id;

  /**
   * FK to Contact ID
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Date stakeholder was added to power map
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $added_date;

  /**
   * FK to Contact ID who added stakeholder
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $added_by;

  /**
   * Is this stakeholder assignment active?
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * X coordinate for manual positioning
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $position_x;

  /**
   * Y coordinate for manual positioning
   *
   * @var float|string|null
   *   (SQL type: decimal(20,2))
   *   Note that values will be retrieved from the database as a string.
   */
  public $position_y;

  /**
   * Additional notes about this stakeholder assignment
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $notes;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_powermap_stakeholder';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Powermap Stakeholders') : E::ts('Powermap Stakeholder');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique PowerMap Stakeholder ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_stakeholder.id',
          'table_name' => 'civicrm_powermap_stakeholder',
          'entity' => 'PowermapStakeholder',
          'bao' => 'CRM_Powermap_DAO_PowermapStakeholder',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'powermap_id' => [
          'name' => 'powermap_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Powermap ID'),
          'description' => E::ts('FK to PowerMap Config'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_stakeholder.powermap_id',
          'table_name' => 'civicrm_powermap_stakeholder',
          'entity' => 'PowermapStakeholder',
          'bao' => 'CRM_Powermap_DAO_PowermapStakeholder',
          'localizable' => 0,
          'FKClassName' => 'CRM_Powermap_DAO_PowermapConfig',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Power Map"),
          ],
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_stakeholder.contact_id',
          'table_name' => 'civicrm_powermap_stakeholder',
          'entity' => 'PowermapStakeholder',
          'bao' => 'CRM_Powermap_DAO_PowermapStakeholder',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Contact"),
          ],
          'add' => NULL,
        ],
        'added_date' => [
          'name' => 'added_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Added Date'),
          'description' => E::ts('Date stakeholder was added to power map'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_stakeholder.added_date',
          'table_name' => 'civicrm_powermap_stakeholder',
          'entity' => 'PowermapStakeholder',
          'bao' => 'CRM_Powermap_DAO_PowermapStakeholder',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
            'label' => E::ts("Added Date"),
          ],
          'add' => NULL,
        ],
        'added_by' => [
          'name' => 'added_by',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Added By'),
          'description' => E::ts('FK to Contact ID who added stakeholder'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_stakeholder.added_by',
          'table_name' => 'civicrm_powermap_stakeholder',
          'entity' => 'PowermapStakeholder',
          'bao' => 'CRM_Powermap_DAO_PowermapStakeholder',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Added By"),
          ],
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Enabled'),
          'description' => E::ts('Is this stakeholder assignment active?'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_stakeholder.is_active',
          'default' => '1',
          'table_name' => 'civicrm_powermap_stakeholder',
          'entity' => 'PowermapStakeholder',
          'bao' => 'CRM_Powermap_DAO_PowermapStakeholder',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
            'label' => E::ts("Active"),
          ],
          'add' => NULL,
        ],
        'position_x' => [
          'name' => 'position_x',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Position X'),
          'description' => E::ts('X coordinate for manual positioning'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_stakeholder.position_x',
          'table_name' => 'civicrm_powermap_stakeholder',
          'entity' => 'PowermapStakeholder',
          'bao' => 'CRM_Powermap_DAO_PowermapStakeholder',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Position X"),
          ],
          'add' => NULL,
        ],
        'position_y' => [
          'name' => 'position_y',
          'type' => CRM_Utils_Type::T_MONEY,
          'title' => E::ts('Position Y'),
          'description' => E::ts('Y coordinate for manual positioning'),
          'precision' => [
            20,
            2,
          ],
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_stakeholder.position_y',
          'table_name' => 'civicrm_powermap_stakeholder',
          'entity' => 'PowermapStakeholder',
          'bao' => 'CRM_Powermap_DAO_PowermapStakeholder',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Position Y"),
          ],
          'add' => NULL,
        ],
        'notes' => [
          'name' => 'notes',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Notes'),
          'description' => E::ts('Additional notes about this stakeholder assignment'),
          'rows' => 3,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_stakeholder.notes',
          'table_name' => 'civicrm_powermap_stakeholder',
          'entity' => 'PowermapStakeholder',
          'bao' => 'CRM_Powermap_DAO_PowermapStakeholder',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Notes"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'powermap_stakeholder', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'powermap_stakeholder', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_powermap_stakeholder' => [
        'name' => 'UI_powermap_stakeholder',
        'field' => [
          0 => 'powermap_id',
          1 => 'contact_id',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_powermap_stakeholder::1::powermap_id::contact_id',
      ],
      'index_powermap_id' => [
        'name' => 'index_powermap_id',
        'field' => [
          0 => 'powermap_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_stakeholder::0::powermap_id',
      ],
      'index_contact_id' => [
        'name' => 'index_contact_id',
        'field' => [
          0 => 'contact_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_stakeholder::0::contact_id',
      ],
      'index_added_by' => [
        'name' => 'index_added_by',
        'field' => [
          0 => 'added_by',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_stakeholder::0::added_by',
      ],
      'index_is_active' => [
        'name' => 'index_is_active',
        'field' => [
          0 => 'is_active',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_stakeholder::0::is_active',
      ],
      'index_added_date' => [
        'name' => 'index_added_date',
        'field' => [
          0 => 'added_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_stakeholder::0::added_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
