<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.powermap/xml/schema/CRM/Powermap/PowermapAssessmentHistory.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:1ed58afe359db236c427a7b050a5050a)
 */
use CRM_Powermap_ExtensionUtil as E;

/**
 * Database access object for the PowermapAssessmentHistory entity.
 */
class CRM_Powermap_DAO_PowermapAssessmentHistory extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_powermap_assessment_history';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique Assessment History ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Contact ID
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * FK to PowerMap Config (optional)
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $powermap_id;

  /**
   * Historical influence level
   *
   * @var string|null
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $influence_level;

  /**
   * Historical support level
   *
   * @var string|null
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $support_level;

  /**
   * Historical engagement priority
   *
   * @var string|null
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $engagement_priority;

  /**
   * Historical stakeholder types
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $stakeholder_type;

  /**
   * Historical assessment notes
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $assessment_notes;

  /**
   * Date of this assessment
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $assessed_date;

  /**
   * FK to Contact ID who made assessment
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $assessed_by;

  /**
   * Reason for assessment change
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $change_reason;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_powermap_assessment_history';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Powermap Assessment Histories') : E::ts('Powermap Assessment History');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique Assessment History ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.id',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Contact ID'),
          'description' => E::ts('FK to Contact ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.contact_id',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Contact"),
          ],
          'add' => NULL,
        ],
        'powermap_id' => [
          'name' => 'powermap_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Powermap ID'),
          'description' => E::ts('FK to PowerMap Config (optional)'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.powermap_id',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'FKClassName' => 'CRM_Powermap_DAO_PowermapConfig',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Power Map"),
          ],
          'add' => NULL,
        ],
        'influence_level' => [
          'name' => 'influence_level',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Influence Level'),
          'description' => E::ts('Historical influence level'),
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.influence_level',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Influence Level"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Powermap_BAO_PowermapAssessmentHistory::getInfluenceLevelOptions',
          ],
          'add' => NULL,
        ],
        'support_level' => [
          'name' => 'support_level',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Support Level'),
          'description' => E::ts('Historical support level'),
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.support_level',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Support Level"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Powermap_BAO_PowermapAssessmentHistory::getSupportLevelOptions',
          ],
          'add' => NULL,
        ],
        'engagement_priority' => [
          'name' => 'engagement_priority',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Engagement Priority'),
          'description' => E::ts('Historical engagement priority'),
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.engagement_priority',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Engagement Priority"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Powermap_BAO_PowermapAssessmentHistory::getEngagementPriorityOptions',
          ],
          'add' => NULL,
        ],
        'stakeholder_type' => [
          'name' => 'stakeholder_type',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Stakeholder Type'),
          'description' => E::ts('Historical stakeholder types'),
          'rows' => 2,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.stakeholder_type',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Stakeholder Type"),
          ],
          'add' => NULL,
        ],
        'assessment_notes' => [
          'name' => 'assessment_notes',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Assessment Notes'),
          'description' => E::ts('Historical assessment notes'),
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.assessment_notes',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'RichTextEditor',
            'label' => E::ts("Assessment Notes"),
          ],
          'add' => NULL,
        ],
        'assessed_date' => [
          'name' => 'assessed_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Assessed Date'),
          'description' => E::ts('Date of this assessment'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.assessed_date',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
            'label' => E::ts("Assessed Date"),
          ],
          'add' => NULL,
        ],
        'assessed_by' => [
          'name' => 'assessed_by',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Assessed By'),
          'description' => E::ts('FK to Contact ID who made assessment'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.assessed_by',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Assessed By"),
          ],
          'add' => NULL,
        ],
        'change_reason' => [
          'name' => 'change_reason',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Change Reason'),
          'description' => E::ts('Reason for assessment change'),
          'rows' => 3,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_assessment_history.change_reason',
          'table_name' => 'civicrm_powermap_assessment_history',
          'entity' => 'PowermapAssessmentHistory',
          'bao' => 'CRM_Powermap_DAO_PowermapAssessmentHistory',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Change Reason"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'powermap_assessment_history', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'powermap_assessment_history', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'index_contact_id' => [
        'name' => 'index_contact_id',
        'field' => [
          0 => 'contact_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_assessment_history::0::contact_id',
      ],
      'index_powermap_id' => [
        'name' => 'index_powermap_id',
        'field' => [
          0 => 'powermap_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_assessment_history::0::powermap_id',
      ],
      'index_assessed_by' => [
        'name' => 'index_assessed_by',
        'field' => [
          0 => 'assessed_by',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_assessment_history::0::assessed_by',
      ],
      'index_assessed_date' => [
        'name' => 'index_assessed_date',
        'field' => [
          0 => 'assessed_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_assessment_history::0::assessed_date',
      ],
      'index_influence_level' => [
        'name' => 'index_influence_level',
        'field' => [
          0 => 'influence_level',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_assessment_history::0::influence_level',
      ],
      'index_support_level' => [
        'name' => 'index_support_level',
        'field' => [
          0 => 'support_level',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_assessment_history::0::support_level',
      ],
      'index_engagement_priority' => [
        'name' => 'index_engagement_priority',
        'field' => [
          0 => 'engagement_priority',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_assessment_history::0::engagement_priority',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
