<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from com.skvare.powermap/xml/schema/CRM/Powermap/PowermapConfig.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:209edf0f9f4e2a61ce6b2db873b4d8e3)
 */
use CRM_Powermap_ExtensionUtil as E;

/**
 * Database access object for the PowermapConfig entity.
 */
class CRM_Powermap_DAO_PowermapConfig extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_powermap_config';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = FALSE;

  /**
   * Unique PowerMap Config ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Power Map Name
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * Power Map Description
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $description;

  /**
   * Associated Campaign ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $campaign_id;

  /**
   * FK to Contact ID of creator
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_id;

  /**
   * Date and time power map was created
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $created_date;

  /**
   * FK to Contact ID of last modifier
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $modified_id;

  /**
   * Date and time power map was last modified
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $modified_date;

  /**
   * Is this power map active?
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_active;

  /**
   * Is this power map reserved?
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_reserved;

  /**
   * Visibility setting (public, private, group)
   *
   * @var string|null
   *   (SQL type: varchar(32))
   *   Note that values will be retrieved from the database as a string.
   */
  public $visibility;

  /**
   * JSON encoded settings for this power map
   *
   * @var string|null
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $settings;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_powermap_config';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Powermap Configs') : E::ts('Powermap Config');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('ID'),
          'description' => E::ts('Unique PowerMap Config ID'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.id',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'description' => E::ts('Power Map Name'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.name',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'Text',
            'label' => E::ts("Power Map Name"),
          ],
          'add' => NULL,
        ],
        'description' => [
          'name' => 'description',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Description'),
          'description' => E::ts('Power Map Description'),
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.description',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Description"),
          ],
          'add' => NULL,
        ],
        'campaign_id' => [
          'name' => 'campaign_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Campaign ID'),
          'description' => E::ts('Associated Campaign ID'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.campaign_id',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'FKClassName' => 'CRM_Campaign_DAO_Campaign',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Campaign"),
          ],
          'add' => NULL,
        ],
        'created_id' => [
          'name' => 'created_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Created ID'),
          'description' => E::ts('FK to Contact ID of creator'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.created_id',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Created By"),
          ],
          'add' => NULL,
        ],
        'created_date' => [
          'name' => 'created_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Created Date'),
          'description' => E::ts('Date and time power map was created'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.created_date',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
            'label' => E::ts("Created Date"),
          ],
          'add' => NULL,
        ],
        'modified_id' => [
          'name' => 'modified_id',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Modified ID'),
          'description' => E::ts('FK to Contact ID of last modifier'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.modified_id',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'html' => [
            'type' => 'EntityRef',
            'label' => E::ts("Modified By"),
          ],
          'add' => NULL,
        ],
        'modified_date' => [
          'name' => 'modified_date',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Modified Date'),
          'description' => E::ts('Date and time power map was last modified'),
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.modified_date',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'Select Date',
            'formatType' => 'activityDateTime',
            'label' => E::ts("Modified Date"),
          ],
          'add' => NULL,
        ],
        'is_active' => [
          'name' => 'is_active',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Enabled'),
          'description' => E::ts('Is this power map active?'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.is_active',
          'default' => '1',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
            'label' => E::ts("Enabled"),
          ],
          'add' => NULL,
        ],
        'is_reserved' => [
          'name' => 'is_reserved',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'title' => E::ts('Is Reserved'),
          'description' => E::ts('Is this power map reserved?'),
          'required' => TRUE,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.is_reserved',
          'default' => '0',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'CheckBox',
            'label' => E::ts("Reserved"),
          ],
          'add' => NULL,
        ],
        'visibility' => [
          'name' => 'visibility',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Visibility'),
          'description' => E::ts('Visibility setting (public, private, group)'),
          'maxlength' => 32,
          'size' => CRM_Utils_Type::MEDIUM,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.visibility',
          'default' => 'public',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'html' => [
            'type' => 'Select',
            'label' => E::ts("Visibility"),
          ],
          'pseudoconstant' => [
            'callback' => 'CRM_Powermap_BAO_PowermapConfig::getVisibilityOptions',
          ],
          'add' => NULL,
        ],
        'settings' => [
          'name' => 'settings',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Settings'),
          'description' => E::ts('JSON encoded settings for this power map'),
          'rows' => 4,
          'cols' => 60,
          'usage' => [
            'import' => FALSE,
            'export' => FALSE,
            'duplicate_matching' => FALSE,
            'token' => FALSE,
          ],
          'where' => 'civicrm_powermap_config.settings',
          'table_name' => 'civicrm_powermap_config',
          'entity' => 'PowermapConfig',
          'bao' => 'CRM_Powermap_DAO_PowermapConfig',
          'localizable' => 0,
          'serialize' => self::SERIALIZE_JSON,
          'html' => [
            'type' => 'TextArea',
            'label' => E::ts("Settings"),
          ],
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'powermap_config', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'powermap_config', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'UI_name' => [
        'name' => 'UI_name',
        'field' => [
          0 => 'name',
        ],
        'localizable' => FALSE,
        'unique' => TRUE,
        'sig' => 'civicrm_powermap_config::1::name',
      ],
      'index_campaign_id' => [
        'name' => 'index_campaign_id',
        'field' => [
          0 => 'campaign_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_config::0::campaign_id',
      ],
      'index_created_id' => [
        'name' => 'index_created_id',
        'field' => [
          0 => 'created_id',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_config::0::created_id',
      ],
      'index_is_active' => [
        'name' => 'index_is_active',
        'field' => [
          0 => 'is_active',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_config::0::is_active',
      ],
      'index_visibility' => [
        'name' => 'index_visibility',
        'field' => [
          0 => 'visibility',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_config::0::visibility',
      ],
      'index_created_date' => [
        'name' => 'index_created_date',
        'field' => [
          0 => 'created_date',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_powermap_config::0::created_date',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
